spring.profiles: test
crypto:
  algorithm: AES
  key: 12345678912345678912345678955555
spring:
  data:
    mongodb:
      username: testuser
      password: 1234
      uri: mongodb://localhost
      port: 27017
      database: testdatabase
      authentication-database: testdatabase
